/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathgameproject;

import javax.swing.JOptionPane;

/**
 *
 * @author mahbubul
 */
public class MulEasy extends javax.swing.JFrame {
    int numOfQues,num1,num2,userAns,realAns,right,wrong;
    String summary = "";
    long startTime,endTime,totalTime;
    /**
     * Creates new form MulEasy
     */
    public MulEasy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayButton = new javax.swing.JButton();
        quesTextField = new javax.swing.JTextField();
        ansjTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlayButton.setBackground(new java.awt.Color(0, 0, 0));
        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgameproject/Play-Now-Button.png"))); // NOI18N
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PlayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 240, 70));

        quesTextField.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        quesTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(quesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, 60));

        ansjTextField.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ansjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(ansjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 200, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgameproject/submit-button-png-1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 120, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgameproject/Exit.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 60, 60));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgameproject/Arrow-Back-icon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgameproject/xp57lq.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        numOfQues = Integer.parseInt( JOptionPane.showInputDialog("How many question do you want???"));
        startTime = System.currentTimeMillis();
        game();
        PlayButton.setVisible(false);
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int exit =  JOptionPane.showConfirmDialog(null,"Are yor sure","Confirm",JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
public void game()
{
                num1 = (int) (Math.random()*20);
                num2 = (int) (Math.random()*20);
                quesTextField.setText(num1+ " * " +num2+ " =  ?");
		realAns = num1 * num2;
}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        MulLevel mulLevel = new MulLevel();
        mulLevel.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        userAns =  Integer.parseInt(ansjTextField.getText());
        summary = summary + "\n" +num1+ " * " +num2+ " = " +userAns+ " : "+(userAns == realAns);
        if (userAns == realAns)
        {
            right++;
            ansjTextField.setText("");
            game();
        }
        else 
        {
            wrong++;
            ansjTextField.setText("");
            game();
        }
        if (right + wrong == numOfQues)
        {
            endTime = System.currentTimeMillis();
            totalTime = endTime - startTime;
            Result result = new Result();
            result.jTextArea.append(summary);
            result.jTextField1.setText(Integer.toString(right));
            result.jTextField3.setText(Integer.toString(wrong));
            result.jTextField2.setText(Long.toString(totalTime /1000));
            result.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MulEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MulEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MulEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MulEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MulEasy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlayButton;
    private javax.swing.JTextField ansjTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField quesTextField;
    // End of variables declaration//GEN-END:variables
}
