/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathgameproject;

import javax.swing.JOptionPane;

/**
 *
 * @author mahbubul
 */
public class RanEasy extends javax.swing.JFrame {
    int numOfQues,num1,num2,right,wrong,random;
    double userAns2,realAns2,userAns,realAns;
    String summary = "";
    long startTime,endTime,totalTime;
    /**
     * Creates new form RanEasy
     */
    public RanEasy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayButton = new javax.swing.JButton();
        questionField = new javax.swing.JTextField();
        ansField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlayButton.setBackground(new java.awt.Color(0, 0, 0));
        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgameproject/Play-Now-Button.png"))); // NOI18N
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PlayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 240, 70));

        questionField.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        questionField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(questionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, 60));

        ansField.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ansField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(ansField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 200, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgameproject/submit-button-png-1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 120, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgameproject/Exit.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 60, 60));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgameproject/Arrow-Back-icon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathgameproject/9259c0314d5ed959765b5276c081f3e0.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        numOfQues = Integer.parseInt( JOptionPane.showInputDialog("How many question do you want???"));
        startTime = System.currentTimeMillis();
        game();
        PlayButton.setVisible(false);
    }//GEN-LAST:event_PlayButtonActionPerformed
public void game()
{
                                num1 = (int)(Math.random()*11);
				num2 = (int)(Math.random()*11);
				random = (int)(Math.random()*4);
				switch (random) 
				{
				case 0:
					questionField.setText(num1+ " + " +num2);
					realAns = num1 + num2;
					break;
				case 1:
					if(num1<num2)
					{
						int temp = num1;
						num1 = num2;
						num2 = temp;
					}
					questionField.setText(num1+ " - " +num2);
					realAns = num1 - num2;
					break;
				case 2:
					questionField.setText(num1+ " * " +num2);
					realAns = num1 * num2;
					break;
				case 3:
					if(num1<num2)
					{
						int temp = num1;
						num1 = num2;
						num2 = temp;
					}
                                       if (num1 ==0 || num2 ==0)
                                        {
                                            num1 += 2;
                                            num2 += 2;
                                        }
						questionField.setText(num1+ " / " +num2);
						realAns2 = (double) num1 / num2;
                                                realAns2 = Math.floor(realAns2 * 100)/100;
						break;
					

				  }
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int exit =  JOptionPane.showConfirmDialog(null,"Are yor sure","Confirm",JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        RanLevel ranLevel = new RanLevel();
        ranLevel.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                userAns2 = Double.parseDouble(ansField.getText());
                                userAns = Double.parseDouble(ansField.getText());
                                switch (random)
                                {
                                    case 0:
                                    summary = summary + "\n" +num1+ " + " +num2+ " = " +userAns+ " : "+(userAns == realAns);
                                    break;
                                    case 1:
                                    summary = summary + "\n" +num1+ " - " +num2+ " = " +userAns+ " : "+(userAns == realAns);
                                    break;
                                    case 2:
                                    summary = summary + "\n" +num1+ " * " +num2+ " = " +userAns+ " : "+(userAns == realAns);
                                    break;
                                    case 3:
                                    summary = summary + "\n" +num1+ " / " +num2+ " = " +userAns2+ " : "+(userAns2 == realAns2);
                                    break;
                                    
                                }
                                if (userAns2 == realAns2 || userAns == realAns)
				{
					right++;
                                        game();
					ansField.setText("");
                                }
                                else if (userAns != realAns)
				{
					
                                        wrong++;
                                        game();
					ansField.setText("");
					
				}
                                else if (userAns2 != realAns2)
				{
					
                                        wrong++;
                                        game();
					ansField.setText("");
					
				}
				if (right + wrong == numOfQues)
				{
					endTime = System.currentTimeMillis();
                                        totalTime = endTime - startTime;
                                        Result result = new Result();
                                        result.jTextArea.append(summary);
                                        result.jTextField1.setText(Integer.toString(right));
                                        result.jTextField1.setText(Integer.toString(wrong));
                                        result.jTextField2.setText(Long.toString(totalTime /1000));
                                        result.setVisible(true);
                                        setVisible(false);
				}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RanEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RanEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RanEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RanEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RanEasy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlayButton;
    private javax.swing.JTextField ansField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField questionField;
    // End of variables declaration//GEN-END:variables
}
