/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturants;

import javax.swing.JOptionPane;

import java.sql.*;
import javax.swing.*;
public class NewJFrame extends javax.swing.JFrame {

   Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public NewJFrame() {
        initComponents();
        conn=Sqlite.ConnecrDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CountryCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Convertxtfield = new javax.swing.JTextField();
        ConvertBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pizzabox = new javax.swing.JCheckBox();
        Burgerbox = new javax.swing.JCheckBox();
        hotDogbox = new javax.swing.JCheckBox();
        pizzafield = new javax.swing.JTextField();
        Burgerfield = new javax.swing.JTextField();
        hotDogfield = new javax.swing.JTextField();
        DrinksCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Sandbox = new javax.swing.JCheckBox();
        Sandfield = new javax.swing.JTextField();
        Teharifield = new javax.swing.JTextField();
        Biryanifield = new javax.swing.JTextField();
        Borhanifield = new javax.swing.JTextField();
        Chickenfield = new javax.swing.JTextField();
        Chickenbox = new javax.swing.JCheckBox();
        Borhanibox = new javax.swing.JCheckBox();
        Biryanibox = new javax.swing.JCheckBox();
        Teharibox = new javax.swing.JCheckBox();
        drinksfield = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Deliverybox = new javax.swing.JCheckBox();
        Costofmealtxtfield = new javax.swing.JTextField();
        CostofDrinkstxtfield1 = new javax.swing.JTextField();
        Costofdeliveryfield = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Printbtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jbtnTotal = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnReciept = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnsubTotal = new javax.swing.JButton();
        SignoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        subTotalField = new javax.swing.JTextField();
        totalField = new javax.swing.JTextField();
        taxField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        CountryCombo.setBackground(new java.awt.Color(0, 0, 0));
        CountryCombo.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        CountryCombo.setForeground(new java.awt.Color(255, 255, 255));
        CountryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Country", "Bangladesh", "Pakistan", "India", "US", "China", "Srilanka", "Singapore", "Japan" }));
        CountryCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryComboActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Country");

        Convertxtfield.setBackground(new java.awt.Color(153, 153, 153));
        Convertxtfield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        Convertxtfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Convertxtfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Convertxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertxtfieldActionPerformed(evt);
            }
        });

        ConvertBtn.setBackground(new java.awt.Color(0, 0, 0));
        ConvertBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ConvertBtn.setForeground(new java.awt.Color(255, 255, 255));
        ConvertBtn.setText("Convert");
        ConvertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Convertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ConvertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(CountryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CountryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Convertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 360, 210));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        pizzabox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pizzabox.setText("Pizza");
        pizzabox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaboxActionPerformed(evt);
            }
        });

        Burgerbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Burgerbox.setText("Burger");
        Burgerbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BurgerboxActionPerformed(evt);
            }
        });

        hotDogbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hotDogbox.setText("Hot Dog");
        hotDogbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotDogboxActionPerformed(evt);
            }
        });

        pizzafield.setBackground(new java.awt.Color(153, 153, 153));
        pizzafield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        pizzafield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pizzafield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pizzafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzafieldActionPerformed(evt);
            }
        });

        Burgerfield.setBackground(new java.awt.Color(153, 153, 153));
        Burgerfield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        Burgerfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Burgerfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Burgerfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BurgerfieldActionPerformed(evt);
            }
        });

        hotDogfield.setBackground(new java.awt.Color(153, 153, 153));
        hotDogfield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        hotDogfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hotDogfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        hotDogfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotDogfieldActionPerformed(evt);
            }
        });

        DrinksCombo.setBackground(new java.awt.Color(0, 0, 0));
        DrinksCombo.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        DrinksCombo.setForeground(new java.awt.Color(255, 255, 255));
        DrinksCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Pepsi", "Cocke", "Fanta", "Mirinda", "Tea", "Coffe" }));
        DrinksCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinksComboActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Drinks");

        Sandbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sandbox.setText("Sandwitch");
        Sandbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SandboxActionPerformed(evt);
            }
        });

        Sandfield.setBackground(new java.awt.Color(153, 153, 153));
        Sandfield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        Sandfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sandfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Sandfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SandfieldActionPerformed(evt);
            }
        });

        Teharifield.setBackground(new java.awt.Color(153, 153, 153));
        Teharifield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        Teharifield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Teharifield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Teharifield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeharifieldActionPerformed(evt);
            }
        });

        Biryanifield.setBackground(new java.awt.Color(153, 153, 153));
        Biryanifield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        Biryanifield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Biryanifield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Biryanifield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiryanifieldActionPerformed(evt);
            }
        });

        Borhanifield.setBackground(new java.awt.Color(153, 153, 153));
        Borhanifield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        Borhanifield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Borhanifield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Borhanifield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorhanifieldActionPerformed(evt);
            }
        });

        Chickenfield.setBackground(new java.awt.Color(153, 153, 153));
        Chickenfield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        Chickenfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Chickenfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Chickenfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenfieldActionPerformed(evt);
            }
        });

        Chickenbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Chickenbox.setText("Chicken");
        Chickenbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenboxActionPerformed(evt);
            }
        });

        Borhanibox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Borhanibox.setText("Borhani");
        Borhanibox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorhaniboxActionPerformed(evt);
            }
        });

        Biryanibox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Biryanibox.setText("Biryani");
        Biryanibox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiryaniboxActionPerformed(evt);
            }
        });

        Teharibox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Teharibox.setText("Tehari");
        Teharibox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TehariboxActionPerformed(evt);
            }
        });

        drinksfield.setBackground(new java.awt.Color(153, 153, 153));
        drinksfield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        drinksfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        drinksfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        drinksfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Sandbox))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Sandfield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drinksfield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(hotDogbox)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hotDogfield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Burgerbox)
                                .addComponent(pizzabox))
                            .addGap(56, 56, 56)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pizzafield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Burgerfield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Borhanibox)
                            .addComponent(Chickenbox)
                            .addComponent(Biryanibox)
                            .addComponent(Teharibox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Borhanifield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Chickenfield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Teharifield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Biryanifield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DrinksCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pizzabox)
                            .addComponent(pizzafield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Chickenbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Burgerbox)
                            .addComponent(Burgerfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Borhanibox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hotDogbox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotDogfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Biryanibox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sandfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sandbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Teharibox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Chickenfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Borhanifield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Biryanifield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Teharifield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinksfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DrinksCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(451, 451, 451))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 500, 240));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cost of meal");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Cost of Drinks");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Cost of Delivery");

        Deliverybox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Deliverybox.setText("Home Delivery");
        Deliverybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryboxActionPerformed(evt);
            }
        });

        Costofmealtxtfield.setEditable(false);
        Costofmealtxtfield.setBackground(new java.awt.Color(153, 153, 153));
        Costofmealtxtfield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        Costofmealtxtfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Costofmealtxtfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Costofmealtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostofmealtxtfieldActionPerformed(evt);
            }
        });

        CostofDrinkstxtfield1.setEditable(false);
        CostofDrinkstxtfield1.setBackground(new java.awt.Color(153, 153, 153));
        CostofDrinkstxtfield1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        CostofDrinkstxtfield1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CostofDrinkstxtfield1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        CostofDrinkstxtfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostofDrinkstxtfield1ActionPerformed(evt);
            }
        });

        Costofdeliveryfield.setEditable(false);
        Costofdeliveryfield.setBackground(new java.awt.Color(153, 153, 153));
        Costofdeliveryfield.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        Costofdeliveryfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Costofdeliveryfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Costofdeliveryfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostofdeliveryfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Costofmealtxtfield, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(CostofDrinkstxtfield1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Costofdeliveryfield, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(Deliverybox)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Costofmealtxtfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CostofDrinkstxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Costofdeliveryfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deliverybox))
                .addGap(147, 147, 147)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 500, 210));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Money Reciept");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Reciept", jPanel7);

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Customer Information");

        jTextField1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel14.setText("Customer Name");

        jLabel15.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel15.setText("Phone");

        jTextField3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel16.setText("Address");

        jTextField4.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel17.setText("Email");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                        .addGap(28, 28, 28))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Info", jPanel8);

        Printbtn.setBackground(new java.awt.Color(0, 0, 0));
        Printbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Printbtn.setForeground(new java.awt.Color(255, 255, 255));
        Printbtn.setText("Print");
        Printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, 440, 600));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jbtnTotal.setBackground(new java.awt.Color(0, 0, 0));
        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTotal.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnReset.setBackground(new java.awt.Color(0, 0, 0));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(255, 255, 255));
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnReciept.setBackground(new java.awt.Color(0, 0, 0));
        jbtnReciept.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReciept.setForeground(new java.awt.Color(255, 255, 255));
        jbtnReciept.setText("Reciept");
        jbtnReciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRecieptActionPerformed(evt);
            }
        });

        jbtnExit.setBackground(new java.awt.Color(0, 0, 0));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(255, 255, 255));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnsubTotal.setBackground(new java.awt.Color(0, 0, 0));
        jbtnsubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnsubTotal.setForeground(new java.awt.Color(255, 255, 255));
        jbtnsubTotal.setText("Sub-Total");
        jbtnsubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsubTotalActionPerformed(evt);
            }
        });

        SignoutBtn.setBackground(new java.awt.Color(0, 0, 0));
        SignoutBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SignoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignoutBtn.setText("Sign Out");
        SignoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jbtnsubTotal)
                .addGap(30, 30, 30)
                .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jbtnReciept, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(SignoutBtn)
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnsubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnReciept, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 870, 130));

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Restaurant Managment System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 850, 90));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Tax");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Total");

        subTotalField.setEditable(false);
        subTotalField.setBackground(new java.awt.Color(153, 153, 153));
        subTotalField.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        subTotalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subTotalField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        totalField.setEditable(false);
        totalField.setBackground(new java.awt.Color(153, 153, 153));
        totalField.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        totalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        taxField.setEditable(false);
        taxField.setBackground(new java.awt.Color(153, 153, 153));
        taxField.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        taxField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        taxField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Sub-Total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 360, 240));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resturants/ydr.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1350, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hotDogfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotDogfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotDogfieldActionPerformed

    private void BurgerboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BurgerboxActionPerformed
            double w = Double.parseDouble(Costofmealtxtfield.getText());
            double r = Double.parseDouble(Burgerfield.getText());
            double burger = 120.00;
            if(Burgerbox.isSelected()){
            double s =w+burger * r;
            Costofmealtxtfield.setText(Double.toString(s));
            }
    }//GEN-LAST:event_BurgerboxActionPerformed

    private void CostofdeliveryfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostofdeliveryfieldActionPerformed
        
    }//GEN-LAST:event_CostofdeliveryfieldActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        int choice=JOptionPane.showConfirmDialog(null,"Are You Sure" , "Message",JOptionPane.YES_NO_OPTION);
        if(choice==JOptionPane.YES_OPTION){
            
            Costofmealtxtfield.setText("0.00");
            CostofDrinkstxtfield1.setText("0.00");
            Costofdeliveryfield.setText("0.00");
            Convertxtfield.setText("");
            subTotalField.setText("");
            taxField.setText("");
            totalField.setText("");
            jTextArea1.setText("");
            pizzabox.setSelected(false);
            Burgerbox.setSelected(false);
            hotDogbox.setSelected(false);
            //Taxbox.setSelected(false);
            Deliverybox.setSelected(false);
            pizzafield.setText("0");
            Burgerfield.setText("0");
            hotDogfield.setText("0");
            Sandfield.setText("0");
            Borhanifield.setText("0");
            Biryanifield.setText("0");
            Teharifield.setText("0");
            Chickenfield.setText("0");
            Sandbox.setSelected(false);
            Borhanibox.setSelected(false);
            Biryanibox.setSelected(false);
            Teharibox.setSelected(false);
            Chickenbox.setSelected(false);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            
            drinksfield.setText("0");
          
            
        }
         
        
        
    }//GEN-LAST:event_jbtnResetActionPerformed
 
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        int choice=JOptionPane.showConfirmDialog(null,"Are You Sure" , "Message",JOptionPane.YES_NO_OPTION);
        if(choice==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void DrinksComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinksComboActionPerformed
        double d=Double.parseDouble(drinksfield.getText());
        double Pepsi = 15*d;
        double Cocke = 35*d;
        double Fanta = 30*d;
        double Mirinda = 30*d;
        double Tea = 10*d;
        double Coffe = 60*d;
        
        if(DrinksCombo.getSelectedItem().equals("Pepsi")){
           String p=String.format("%.2f", Pepsi);
           CostofDrinkstxtfield1.setText(p);
        }
        if(DrinksCombo.getSelectedItem().equals("Cocke")){
           String c=String.format("%.2f", Cocke);
           CostofDrinkstxtfield1.setText(c);
        }
        if(DrinksCombo.getSelectedItem().equals("Fanta")){
           String f=String.format("%.2f", Fanta);
           CostofDrinkstxtfield1.setText(f);
        }
        if(DrinksCombo.getSelectedItem().equals("Mirinda")){
           String m=String.format("%.2f", Mirinda);
           CostofDrinkstxtfield1.setText(m);
        }
        if(DrinksCombo.getSelectedItem().equals("Tea")){
           String t=String.format("%.2f", Tea);
           CostofDrinkstxtfield1.setText(t);
        }
        if(DrinksCombo.getSelectedItem().equals("Coffe")){
           String cf=String.format("%.2f", Coffe);
           CostofDrinkstxtfield1.setText(cf);
        }
        
    }//GEN-LAST:event_DrinksComboActionPerformed

    private void CountryComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryComboActionPerformed
        
    }//GEN-LAST:event_CountryComboActionPerformed

    private void ConvertxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConvertxtfieldActionPerformed

    private void DeliveryboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryboxActionPerformed
        String delivery = "50.00 ";
        Costofdeliveryfield.setText(delivery);
    }//GEN-LAST:event_DeliveryboxActionPerformed

    private void pizzaboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaboxActionPerformed
            double y = Double.parseDouble(Costofmealtxtfield.getText());
            double r = Double.parseDouble(pizzafield.getText());
            double pizza = 150.00;
            if(pizzabox.isSelected()){ 
            double s = y + pizza * r;
            Costofmealtxtfield.setText(Double.toString(s));
             
            }
            
            
       
        
       
    }//GEN-LAST:event_pizzaboxActionPerformed

    private void BurgerfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BurgerfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BurgerfieldActionPerformed

    private void hotDogboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotDogboxActionPerformed
       
            double x = Double.parseDouble(Costofmealtxtfield.getText());
            double r = Double.parseDouble(hotDogfield.getText());
            double hotDog = 80.00;
            if(hotDogbox.isSelected()){ 
            double s = x + (hotDog* r);
            Costofmealtxtfield.setText(Double.toString(s));
            }
        
    }//GEN-LAST:event_hotDogboxActionPerformed

    private void CostofmealtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostofmealtxtfieldActionPerformed
        
    }//GEN-LAST:event_CostofmealtxtfieldActionPerformed

    private void pizzafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pizzafieldActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        double m=Double.parseDouble(Costofmealtxtfield.getText());
        double d=Double.parseDouble(CostofDrinkstxtfield1.getText());
        double de=Double.parseDouble(Costofdeliveryfield.getText());
        double tax=0.05;
        double sum=(m+d)*tax;
        double total=sum+m+d+de;
        String taxfiel = "5.00%"; taxField.setText(taxfiel);
        totalField.setText(Double.toString(total));
        
         
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void CostofDrinkstxtfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostofDrinkstxtfield1ActionPerformed
         
    }//GEN-LAST:event_CostofDrinkstxtfield1ActionPerformed

    private void jbtnRecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRecieptActionPerformed
         double m=Double.parseDouble(Costofmealtxtfield.getText());
         double d=Double.parseDouble(CostofDrinkstxtfield1.getText());
         double de=Double.parseDouble(Costofdeliveryfield.getText());
         double t=0.05;
         double tax=(m+d)*t;
         double Pizza=150.00*Double.parseDouble(pizzafield.getText());
         double Hotdog=80.00*Double.parseDouble(hotDogfield.getText());
         double Burger=120.00*Double.parseDouble(Burgerfield.getText());
         double Chicken=130.00*Double.parseDouble(Chickenfield.getText());
         double Borhani=280.00*Double.parseDouble(Borhanifield.getText());
         double Sandwitch=180.00*Double.parseDouble(Sandfield.getText());
         double Biryani=250.00*Double.parseDouble(Biryanifield.getText());
         double Tehari=170.00*Double.parseDouble(Teharifield.getText());
         jTextArea1.append("  RESTURANT MANAGEMENT SYSTEM\n\n\n");
         jTextArea1.append("  Name         Price      Quantity        Cost\n\n");
         jTextArea1.append(".....................................................................\n");
         jTextArea1.append("  Pizza           150            "+pizzafield.getText()+"             =   "+Pizza+"\n");
         jTextArea1.append("  Burger        120            "+Burgerfield.getText()+"             =   "+Burger+"\n");
         jTextArea1.append("  Hotdog        80             "+hotDogfield.getText()+"             =   "+Hotdog+"\n");
         jTextArea1.append("  Sandwitch 180            "+Sandfield.getText()+"             =   "+Sandwitch+"\n");
         jTextArea1.append("  Chicken     130            "+Chickenfield.getText()+"             =   "+Chicken+"\n");
         jTextArea1.append("  Borhani      280            "+Borhanifield.getText()+"             =   "+Borhani+"\n");
         jTextArea1.append("  Biryani        250            "+Biryanifield.getText()+"             =   "+Biryani+"\n");
         
         jTextArea1.append("  Tehari         170            "+Teharifield.getText()+"             =   "+Tehari+"\n\n");
         jTextArea1.append("  Drinks                                           =   "+d+"\n");
         jTextArea1.append("  Tax                                                 =   "+tax+"\n\n");
         jTextArea1.append("  Delivery Charge                          =   "+de+"\n");
         
         jTextArea1.append(".....................................................................\n");
         
         jTextArea1.append("                         \tTotal          = BDT   "+totalField.getText()+"\n");
         try{
           String query="insert into  Sale2(Ammount)values(?)";
           pst=conn.prepareStatement(query);
           pst.setString(1,totalField.getText());
           //pst.setString(2,jTextField2.getText());
           pst.execute();
           
          
        JOptionPane.showMessageDialog(null, "Successful");
         
           pst.close();
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_jbtnRecieptActionPerformed

    private void jbtnsubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsubTotalActionPerformed
        double m=Double.parseDouble(Costofmealtxtfield.getText());
        double d=Double.parseDouble(CostofDrinkstxtfield1.getText());
        double de=Double.parseDouble(Costofdeliveryfield.getText());
        double sub=(m+d+de);
        subTotalField.setText(Double.toString(sub));
    }//GEN-LAST:event_jbtnsubTotalActionPerformed

    private void SandboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SandboxActionPerformed
       double x = Double.parseDouble(Costofmealtxtfield.getText());
            double Sandwitch = 180.00;
            double r = Double.parseDouble(Sandfield.getText());
             if(Sandbox.isSelected()){ 
            double s = x + (Sandwitch* r);
            Costofmealtxtfield.setText(Double.toString(s));
             }
           
    }//GEN-LAST:event_SandboxActionPerformed

    private void SandfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SandfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SandfieldActionPerformed

    private void TeharifieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeharifieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeharifieldActionPerformed

    private void BiryanifieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiryanifieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiryanifieldActionPerformed

    private void BorhanifieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorhanifieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorhanifieldActionPerformed

    private void ChickenfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChickenfieldActionPerformed

    private void ChickenboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenboxActionPerformed
            double x = Double.parseDouble(Costofmealtxtfield.getText());
            double r = Double.parseDouble(Chickenfield.getText());
            double Chicken = 130.00;
             if(Chickenbox.isSelected()){ 
            double s = x + (Chicken * r);
            Costofmealtxtfield.setText(Double.toString(s));
             }
    }//GEN-LAST:event_ChickenboxActionPerformed

    private void BorhaniboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorhaniboxActionPerformed
        double x = Double.parseDouble(Costofmealtxtfield.getText());
            double Borhani = 280.00;
            double r = Double.parseDouble(Borhanifield.getText());
            if(Borhanibox.isSelected()){ 
            double s = x + (Borhani * r);
            Costofmealtxtfield.setText(Double.toString(s));
            }
    }//GEN-LAST:event_BorhaniboxActionPerformed

    private void BiryaniboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiryaniboxActionPerformed
        double x = Double.parseDouble(Costofmealtxtfield.getText());
            double Biryani = 250.00;
             
            double r = Double.parseDouble(Biryanifield.getText());
             if(Biryanibox.isSelected()){ 
            double s = x + (Biryani * r);
            Costofmealtxtfield.setText(Double.toString(s));
             }
    }//GEN-LAST:event_BiryaniboxActionPerformed

    private void TehariboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TehariboxActionPerformed
        double x = Double.parseDouble(Costofmealtxtfield.getText());
            double Tehari = 170.00;
            double r = Double.parseDouble(Teharifield.getText());
            if(Teharibox.isSelected()){ 
            double s = x + (Tehari * r);
            Costofmealtxtfield.setText(Double.toString(s));
            }
    }//GEN-LAST:event_TehariboxActionPerformed

    private void PrintbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintbtnActionPerformed
        int choice=JOptionPane.showConfirmDialog(null,"Are You Sure", "Message",JOptionPane.YES_NO_OPTION);
        if(choice==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,"Processing.....");
        }
        else{
            return;
        }
    }//GEN-LAST:event_PrintbtnActionPerformed

    private void ConvertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertBtnActionPerformed
        double British_Pound=Double.parseDouble(Convertxtfield.getText());
         if(CountryCombo.getSelectedItem().equals("Bangladesh")){
             String c=String.format("BD %.2f",British_Pound);
             Convertxtfield.setText(c);
         }
         if(CountryCombo.getSelectedItem().equals("Pakistan")){
             String c=String.format("PKR %.2f",British_Pound*1.31);
             Convertxtfield.setText(c);
         }
         if(CountryCombo.getSelectedItem().equals("India")){
             String c=String.format("INR %.2f",British_Pound*0.81);
             Convertxtfield.setText(c);
         }
         if(CountryCombo.getSelectedItem().equals("US")){
             String c=String.format("USD %.2f",British_Pound*0.0125);
             Convertxtfield.setText(c);
         }
         if(CountryCombo.getSelectedItem().equals("Srilanka")){
             String c=String.format("LKR %.2f",British_Pound*1.8695);
             Convertxtfield.setText(c);
         }
         if(CountryCombo.getSelectedItem().equals("Singapore")){
             String c=String.format("SGD %.2f",British_Pound*0.0174);
             Convertxtfield.setText(c);
         }
         if(CountryCombo.getSelectedItem().equals("China")){
             String c=String.format("CNY %.2f",British_Pound*0.0859);
             Convertxtfield.setText(c);
         }
         if(CountryCombo.getSelectedItem().equals("Japan")){
             String c=String.format("JPY %.2f",British_Pound*1.389);
             Convertxtfield.setText(c);
         }
    }//GEN-LAST:event_ConvertBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Convertxtfield.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
           String query="insert into  Info2(Name,Phone,Address,Email)values(?,?,?,?)";
           pst=conn.prepareStatement(query);
           pst.setString(1,jTextField1.getText());
           pst.setString(2,jTextField2.getText());
           pst.setString(3,jTextField3.getText());
           pst.setString(4,jTextField4.getText());
           //pst.setString(5,jTextField5.getText());
           pst.execute();
           
          
        JOptionPane.showMessageDialog(null, "Successful");
         
           pst.close();
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void drinksfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinksfieldActionPerformed

    private void SignoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignoutBtnActionPerformed
       int choice=JOptionPane.showConfirmDialog(null,"Are You Sure", "Message",JOptionPane.YES_NO_OPTION);
        if(choice==JOptionPane.YES_OPTION){
            //JOptionPane.showMessageDialog(null,"Processing.....");
             LogIn L=new LogIn();
             L.setVisible(true);
             dispose();
        }
        else{
            return;
        }
        
    }//GEN-LAST:event_SignoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Biryanibox;
    public javax.swing.JTextField Biryanifield;
    private javax.swing.JCheckBox Borhanibox;
    public javax.swing.JTextField Borhanifield;
    private javax.swing.JCheckBox Burgerbox;
    public javax.swing.JTextField Burgerfield;
    private javax.swing.JCheckBox Chickenbox;
    public javax.swing.JTextField Chickenfield;
    private javax.swing.JButton ConvertBtn;
    private javax.swing.JTextField Convertxtfield;
    public javax.swing.JTextField CostofDrinkstxtfield1;
    public javax.swing.JTextField Costofdeliveryfield;
    public javax.swing.JTextField Costofmealtxtfield;
    private javax.swing.JComboBox<String> CountryCombo;
    private javax.swing.JCheckBox Deliverybox;
    private javax.swing.JComboBox<String> DrinksCombo;
    private javax.swing.JButton Printbtn;
    private javax.swing.JCheckBox Sandbox;
    public javax.swing.JTextField Sandfield;
    private javax.swing.JButton SignoutBtn;
    private javax.swing.JCheckBox Teharibox;
    public javax.swing.JTextField Teharifield;
    public javax.swing.JTextField drinksfield;
    private javax.swing.JCheckBox hotDogbox;
    public javax.swing.JTextField hotDogfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReciept;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JButton jbtnsubTotal;
    private javax.swing.JCheckBox pizzabox;
    public javax.swing.JTextField pizzafield;
    private javax.swing.JTextField subTotalField;
    private javax.swing.JTextField taxField;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
